// Generated by CoffeeScript 1.6.3
var Q, request;

Q = require('q');

request = require('request');

exports.parse = function(zip) {
  var deferred;
  deferred = Q.defer();
  request.get("http://zip.elevenbasetwo.com/v2/US/" + zip, function(err, res, body) {
    if (err) {
      return deferred.reject(new Error(err));
    } else {
      return deferred.resolve(JSON.parse(body));
    }
  });
  return deferred.promise;
};
